name: Deploy API

on:
  push:
    branches: ["master"]
    paths: [".gitea/workflows/deploy-api.yml", "API/**", "!API/README.md", "!README.md", "!LICENSE.md"]

jobs:
  deploy:
    strategy:
      matrix:
        arch: ["ubuntu-latest"]
        git-version: ["2.44.0"]
    runs-on: ${{ matrix.arch }}
    defaults:
      run:
        working-directory: "./API"

    # Steps to run
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deploy to Dokku
      - name: Deploy to Dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@10.10.3.28:22/tether-api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
