# Server Configuration
server:
  address: 0.0.0.0
  port: 7500

# Log Configuration
logging:
  file:
    path: "./logs"

# Discord Configuration
discord:
  # The user account token also for general API calls
  user-account-token: "CHANGE_ME"

  # The bot token for realtime API calls (online status, activities, etc)
  bot-token: "CHANGE_ME"

# Spring Configuration
spring:
  # Ignore
  banner:
    location: "classpath:banner.txt"